### ISSUE TITLE
 User unable to delete media

### ISSUE THREAD

**Issue by alder** [letterpad/letterpad#107]
### Issue Summary

User unable to delete media from admin panel.

### To Reproduce

1.  Login to Admin dashboard as demo user
2.  Go to Media page
3.  Select 1 or more media items
4.  Press Delete

**ER:** Media items should be successfully deleted.
**AR:** Server error. Media items are not deleted.

### Technical details:

-   Node Version: v10.15.0
-   Browser/OS: Firefox / Ubuntu
-   Database: SQLite

Error log:
```
[0] { Error: Invalid value { in: [ '12' ] }
[0]     at Object.escape (letterpad/node_modules/sequelize/lib/sql-string.js:66:11)
[0]     at Object.escape (letterpad/node_modules/sequelize/lib/dialects/abstract/query-generator.js:936:22)
[0]     at Object._whereParseSingleValueObject (letterpad/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2432:41)
[0]     at Object.whereItemQuery (letterpad/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2136:21)
[0]     at Utils.getComplexKeys.forEach.prop (letterpad/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1997:25)
[0]     at Array.forEach (<anonymous>)
[0]     at Object.whereItemsQuery (letterpad/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1995:35)
[0]     at Object.getWhereConditions (letterpad/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2459:19)
[0]     at Object.deleteQuery (letterpad/node_modules/sequelize/lib/dialects/sqlite/query-generator.js:274:28)
[0]     at QueryInterface.bulkDelete (letterpad/node_modules/sequelize/lib/query-interface.js:1095:37)
[0]     at Promise.try.then.then (letterpad/node_modules/sequelize/lib/model.js:2559:36)
[0]     at tryCatcher (letterpad/node_modules/bluebird/js/release/util.js:16:23)
[0]     at Promise._settlePromiseFromHandler (letterpad/node_modules/bluebird/js/release/promise.js:512:31)
[0]     at Promise._settlePromise (letterpad/node_modules/bluebird/js/release/promise.js:569:18)
[0]     at Promise._settlePromise0 (letterpad/node_modules/bluebird/js/release/promise.js:614:10)
[0]     at Promise._settlePromises (letterpad/node_modules/bluebird/js/release/promise.js:694:18)
[0]     at _drainQueueStep (letterpad/node_modules/bluebird/js/release/async.js:138:12)
[0]     at _drainQueue (letterpad/node_modules/bluebird/js/release/async.js:131:9)
[0]     at Async._drainQueues (letterpad/node_modules/bluebird/js/release/async.js:147:5)
[0]     at Immediate.Async.drainQueues [as _onImmediate] (letterpad/node_modules/bluebird/js/release/async.js:17:14)
[0]     at runCallback (timers.js:705:18)
[0]     at tryOnImmediate (timers.js:676:5)
[0]   message: 'Invalid value { in: [ \'12\' ] }',
[0]   locations: [ { line: 2, column: 3 } ],
[0]   path: [ 'deleteMedia' ] }
```

**Comment by ajaxtown** [comment]
Thanks @alder for fixing this.

Also, there is another development work going on with the editor which you will find here - https://github.com/letterpad/editor

This editor is an abstraction of the editor that was used in letterpad and it has more features like gallery, image variations, inserting image from giphy service, etc.. Eventually we will add that editor as a dependency in this letterpad cms. So some really interesting development over there.

**Comment by alder** [comment]
Hi, @ajaxtown
Yes, I saw you great work with editor! I've some issues in Letterpad which I would like to investigate and fix. And after this it would be great to integrate new enhanced editor in to Letterpad.
